---

- name: create mongo_rs
  shell: >
    /usr/bin/mongo --eval 'printjson(rs.initiate( { _id : "{{ rs_name }}",    members: [       { _id: 0, host: "{{ host_1 }}:27017" },       { _id: 1, host: "{{ host_2 }}:27017" },       { _id: 2, host: "{{ host_3 }}:27017" }    ] }))'
 
